name = "OrdinalIndexing"
uuid = "25bc8f2f-c466-495f-aeec-a8037da7da40"
authors = ["Jishnu Bhattacharya <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]

[compat]
OffsetArrays = "1"
julia = "1"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
