name = "OrdinalIndexing"
uuid = "25bc8f2f-c466-495f-aeec-a8037da7da40"
authors = ["Jishnu Bhattacharya <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
